name: bank_kuningan
description: "A high-fidelity Material Design 3 mobile banking application UI for Bank Kuningan."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bank-kuningan-logo.png
    - assets/images/alto-logo.png
    - assets/images/atm-bersama-logo.png
    - assets/images/bjb-logo.png
    - assets/images/prima-logo.png
